version: '3.8'

services:
  derper:
    image: ghcr.io/monlor/derper-acme:main
    container_name: derper
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "3478:3478/udp"
    volumes:
      - app_data:/app/acme
    environment:
      # DERPER Server Configuration
      - DERPER_DOMAIN=${DERPER_DOMAIN:-your-domain.com}
      - DERPER_CERT_DIR=/app/acme/derper
      - DERPER_ADDR=${DERPER_ADDR:-:443}
      - DERPER_HTTP_PORT=${DERPER_HTTP_PORT:-80}
      - DERPER_STUN=${DERPER_STUN:-true}
      - DERPER_STUN_PORT=${DERPER_STUN_PORT:-3478}
      - DERPER_VERIFY_CLIENTS=${DERPER_VERIFY_CLIENTS:-false}
      
      # ACME Configuration
      - ACME_ENABLED=${ACME_ENABLED:-false}
      - ACME_EMAIL=${ACME_EMAIL:-your-email@example.com}
      - ACME_DNS_PROVIDER=${ACME_DNS_PROVIDER:-cf}
      
      # Cloudflare DNS Provider
      - CF_Token=${CF_Token:-}
      
      # Aliyun DNS Provider
      - Ali_Key=${Ali_Key:-}
      - Ali_Secret=${Ali_Secret:-}
      
      # DNSPod DNS Provider
      - DP_Id=${DP_Id:-}
      - DP_Key=${DP_Key:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DERPER_HTTP_PORT:-80}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - derper_network

volumes:
  app_data:
    driver: local

networks:
  derper_network:
    driver: bridge